inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - test/dummy/db/schema.rb
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: true

Layout/LineLength:
  Max: 80

Style/Documentation:
  Include:
    - app/**/*.rb
    - lib/**/*.rb

Style/DocumentationMethod:
  Include:
    - app/**/*.rb
    - lib/**/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
