inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - test/dummy/db/schema.rb
    - vendor/**/*
  SuggestExtensions: false
  NewCops: disable

Bundler/OrderedGems:
  Enabled: true

Layout/LineLength:
  Max: 80

Style/Documentation:
  Enabled: true
  Include:
    - app/**/*.rb
    - lib/**/*.rb

Style/DocumentationMethod:
  Enabled: true
  Include:
    - app/**/*.rb
    - lib/**/*.rb

Style/HashSyntax:
  Enabled: false
