inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - test/dummy/db/schema.rb
    - vendor/**/*
  SuggestExtensions: false
  NewCops: disable

Bundler/OrderedGems:
  Enabled: true

Style/Documentation:
  Enabled: true
  Include:
    - app/**/*.rb
    - lib/**/*.rb

Style/DocumentationMethod:
  Enabled: true
  Include:
    - app/**/*.rb
    - lib/**/*.rb
